name: Create Tag and Release
on:
  workflow_dispatch:
    inputs:
      TAG:
        required: true
        type: string
        description: Tag to be applied, for example 1.0.0
      CHANGELOG:
        required: true
        type: string
        description: Enter as a list using '- ' and '\n' (e.g. "- First item\n- Second item".). Don't use ' or ". 
      COMMIT:
        type: string
        description: full commit hash, if none supplied, latest main is taken

jobs:
  create-tag:
    runs-on: "ubuntu-latest"
    permissions: 
      contents: write
    steps:
      - name: Determine checkout ref
        run: |
          if [[ -z "${{ inputs.COMMIT }}" ]]; then
            echo "CHECKOUT_REF=main" >> $GITHUB_ENV
          else
            echo "CHECKOUT_REF=${{ inputs.COMMIT }}" >> $GITHUB_ENV
          fi
          
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.CHECKOUT_REF }}
          path: ./Checkout
          
      - name: Create tag
        run: |
          cd ./Checkout
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "${{ inputs.TAG }}" "${{ env.CHECKOUT_REF }}"
          git push origin "${{ inputs.TAG }}"
          cd -
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    uses: VRLabs/Workflows-collection/.github/workflows/VRC-Asset-Release-And-Upload.yml@add-new-workflow
    with:
      ASSETS_PATH: .
      TAG: ${{ inputs.TAG }}
      CHANGELOG: ${{ inputs.CHANGELOG }}
      REPOSITORY: ${{ github.repository }}
      CHECKOUT_REF: ${{ inputs.CHECKOUT_REF }}
    secrets: inherit
    needs: create-tag
