on:
  workflow_dispatch:
    inputs:
      TAG:
        required: true
        type: string
        description: Tag to be applied, for example 1.0.0
      CHANGELOG:
        required: true
        type: string
      COMMIT:
        type: string
        description: full commit hash, if none supplied, latest main is taken

jobs:
  create-tag:
    runs-on: "ubuntu-latest"
    permissions: 
      contents: write
    steps:
      - name: Determine input
        run: |
          if [[ -z "${{ inputs.COMMIT }}" ]]; then
            echo "CHECKOUT_REF=main" >> $GITHUB_ENV
          else
            echo "CHECKOUT_REF=${{ inputs.COMMIT }}" >> $GITHUB_ENV
          fi
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.CHECKOUT_REF }}
          path: ./Assets
      - name: Create tag

        run: |
          cd ./Assets
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "${{ inputs.TAG }}" "${{ env.CHECKOUT_REF }}"
          git push origin "${{ inputs.TAG }}"
          cd -
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    uses: VRLabs/Workflows-collection/.github/workflows/VRC-Asset-Release-And-Upload.yml@add-new-workflow
    with:
      ASSETS_PATH: ./Assets
      RELEASE_PATH: Packages 
      ARTIFACT_DURATION: 30 # In days
      UPLOAD_ENDPOINT: https://api.vrlabs.dev/packages/add
      TAG: ${{ inputs.TAG }}
      CHANGELOG: ${{ inputs.CHANGELOG }}
      REPOSITORY: ${{ github.repository }}
    secrets: inherit
